host_electrumx: 120.79.185.20
port_electrumx: 50001
listen_port: 8888
blocknum: 500
normal: 2
priority: 3
quick: 5
rpcuser: btc
rpcpassword: blockchain
rpcport: 8332
rpcaddress: 39.108.13.219
notify_server_address: https://push.eospark.com
unconfirmed_transaction_interval: 5